config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :articles

  get 'signup' => 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destory]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50 }
  validates :description, presence: true, length: {minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  #validates :name, uniqueness: true --same as the line below
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  
  before_save {self.email = email.downcase}

  validates :username, presence: true, uniqueness: {case_sensitive: false},
   length: {minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\a-z\d\-.]+\.[a-z]+\z/

  validates :email, presence: true, uniqueness:{case_sensitive: false},
    length: {maximum: 150 },
      format: { with: VALID_EMAIL_REGEX}

  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?# [method] => need to return true or false only
  !!current_user# return current _user => ie  true/false or nil
  end

  def require_user
    if !logged_in?
      flash[:danger] = "you must be logged into perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_params, only: [:edit, :show, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only:[:edit, :show, :destroy]
  

  def index
    @All_Articles = Article.paginate(page: params[:page], per_page: 5)
    # byebug
  end

  def new
    @new = Article.new
  end

  def edit
    @edit = @article
    # redirect_to edit_article_path(@edit)
  end


  def create
    # render text: params[:article].inspect
    @new_article = Article.new(params_article)
    @new_article.user = current_user

    if @new_article.save
      flash[:success] = "Article was successfully created"  
      redirect_to article_path(@new_article)
    else
      # byebug
      @new = @new_article
      render 'new'
    end
  end

  def show
   @show = @article
    
  end

  def update
    # render text: params[:article].inspect

    @update = @article
    # byebug
    if @update.update(params_article)
      flash[:success] = "Article was successfully Updated"
      redirect_to article_path(@update)
    else
      @edit = @update
      render 'edit'
    end
  end

  def destroy
    @destory = @article
    id = @destory.id
    @destory.destroy
    flash[:danger] =  "Article #{id} was successfully Deleted"
    redirect_to articles_path

  end

  private

    def set_params
      @article = Article.find(params[:id])
    end
    def params_article
        params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "Dude you cant access the page"
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :require_admin, except: [:index, :show]

    def index
      @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category was created successfully"
        redirect_to categories_path
      else
      render 'new'
      end

    end

    def show

    end

    private

    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
      end

    end

  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create

    email =  User.find_by(email: params[:sessions][:email].downcase)
    # debugger
    if email
    # if email && email.authenticate(params[:sessions][:password_digest])
    session[:user_id] = email.id
    flash[:success] = "You have SUCCESSFULL SIGN IN BUD :)"
    redirect_to user_path(email) 
    else
      flash.now[:danger] = "there was something worng with your email or password"
      render 'new'
    end
  end
  def destroy
    session[:user_id]  = nil
    flash[:success] = "You have Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show] 
  before_action :require_user_same, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destory]
  def index
    @All_users = User.paginate(page: params[:page], per_page: 5)
  end
  def new
    @new_user = User.new
  end

  def edit
    @edit = @user
  end

  def update
    @update = @user
    if @update.update(user_params)
      flash[:success] = "your account has been update successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def create
    # debugger
    @create_user = User.new(user_params)
    # debugger
    if @create_user.save
      session[:user_id] = @create_user.id
      flash[:success] = "You have signed up => congrat #{@create_user.username}"
      redirect_to user_path(@create_user)
    else

      render 'new'
    end

  end

  def show
    @show = @user
    @show_articles = @show.articles.paginate(:page => params[:page],per_page: 5)
  end

  def destroy
    @user_destory = User.find(params[:id])
    @user_destory.destroy
    flash[:danger] = "User and all articles will be deleted"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password_digest)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_user_same
      if current_user != @user && !current_user.admin?
        flash[:danger] = "User has to be logged in dude"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
      flash[:danger] = "Only Admin can delete Users"
      redirect_to root_path
      end      
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravator_for user, option= {size: num}
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, :class => 'img-circle')
  end
end

app/views/articles/_form.html.erb
<div class='row'>
  <div class="col-xs-10">
    <%= form_for(@article, :html => {:class => "form-horizontal", role: "form" }) do |f| %>
      <div class='form-group'>
        <div class="control-label col-sm-2">
            <%= f.label :title %>
        </div>
        <div class="col-sm-5">
            <%= f.text_field :title, :class=> "form-control", :placeholder => "Title of Article" , :autofocus => true%>
        </div>
      </div>
      <div class='form-group'>
        <div class="control-label col-sm-2">
            <%= f.label :description %>
         </div>
        <div class="col-sm-10">
            <%= f.text_area :description, :class=> "form-control", :placeholder => "Body of article" , :autofocus => true, :rows => 10 %>
        </div>
      </div>
      <div class='form-group'>
        <div class=" col-sm-offset-2 col-sm-10">
            <%= f.submit :class => "btn btn-primary btn-lg" %>
        </div>
      </div>

       <div class=" col-sm-offset-2 col-sm-10">
         [ <%= link_to "Back to Home", articles_path %> ]
      </div>

    <% end %>
  </div>
</div>

app/views/articles/_user_articles.html.erb
<div align ='center'>

  <%= will_paginate obj,  :renderer => BootstrapPagination::Rails%>

</div>
<% obj.each do |list| %>

    <div class="row">
      <div class = "col-xs-8 col-xs-offset-2">
        <div class= "well well-lg">
          <div class ="article-title">
            Created by: <%= list.user.username if list.user %> ||
            <br>
            Created  at: <%= time_ago_in_words(list.created_at) %>   || 
            <br>
            Last UpDated:  <%= time_ago_in_words(list.updated_at) %>
            Client id: <%= list.id %> <br>
            Title: <%= link_to list.title, article_path(list) %>
          </div>
          <div class= 'article-body'>
            Description: <%= truncate(list.description, length: 100) %>
          </div>
          <% if logged_in? && (current_user == list.user || current_user.admin?) %>
               <div class="article-action">
            
                  <%= link_to 'Edit all Article', edit_article_path(list), class: "btn btn-ls btn-primary"  %>
                  <%= link_to 'Delete Article', article_path(list), method: :delete,
                            data: { confirm: 'Are you sure?' }, 
                                class: "btn btn-ls btn-danger"  %>

                </div>
            <% end %>
          </div>
      </div>
    </div>
  <% end %>

app/views/articles/edit.html.erb
<h1 align = 'center'> Edit existing article</h1>
 
  <% @article = @edit %>
  <%= render 'shared/error_messages_flash' , obj: @article %>
  <%= render 'form' %>

app/views/articles/index.html.erb
<h1> List of all the Article</h1>

<%= render 'user_articles', :obj => @All_Articles %>

app/views/articles/new.html.erb
  <h1 align = 'center'>Create an article</h1>


<% @article = @new %>
<%= render 'shared/error_messages_flash', obj: @article %>
<%= render 'form' %>

app/views/articles/show.html.erb
  <h2 align = "center">Title: <%= @show.title %> </h2> 
  <div class="well col-xs-8 col-xs-offset-2" >
    <ul class= 'listing'>
        <div class= "row center" >
          <li>Created By :</li>
          <% if @show.user %>
          <div class= " col-md-4 col-md-offset-4">
            <li><%= link_to gravator_for(@show.user, :size => 100), user_path(@show.user) %></li>
            <li class= 'article-title'><%= link_to @show.user.username, user_path(@show.user) %> </li>
            <li><small><%= pluralize(@show.user.articles.count, 'article') if @show.user.articles %> </small></li>
          </div>
          <% end %>
        </div>
      </ul>
    <h4 class="center"> <strong>Description:</strong></h4>
    <hr>
    <h5 class= 'description'><%= simple_format(@show.description) %></h5>
    <div class="article-action">
    <% if logged_in? && (current_user == @show.user || current_user.admin?) %>
        <%= link_to 'View List of Articles', articles_path, class: 'btn btn-ls btn-success' %> 
        <%= link_to 'Edit Article', edit_article_path(@show), class: "btn btn-ls btn-primary"  %>
        <%= link_to 'Delete Article', article_path(@show), method: :delete ,
              data: { confirm: 'Are you sure?' }, 
                  class: "btn btn-ls btn-danger"  %>
      <% end%>
    </div>
  </div>

app/views/categories/index.html.erb
<h1 align='center'>Listing of all the Categoriess</h1>

<% @categories.each do |category| %>
  <ul class = 'listing'>
    <div class = 'row'>
      <div class = "well col-md-4 col-md-offset-4">
        <li class = 'article-title'>
          <%= link_to category.name, category_path(category) %>
        </li>
      </div>
    </div>    
  </ul>
  <% end %>

app/views/categories/new.html.erb
<h1 align= 'center'> Create a new Category</h1>

<div class='row'>
  <div class="col-xs-10">
    <%= form_for(@category, :html => {:class => "form-horizontal", role: "form" }) do |f| %>
      <div class='form-group'>
        <div class="control-label col-sm-2">
            <%= f.label :name%>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :name, :class=> "form-control", :placeholder => "Category Name" , :autofocus => true%>
        </div>
      </div>
    
      </div>
      <div class='form-group'>
        <div class=" col-sm-offset-4 col-sm-8">
            <%= f.submit :class => "btn btn-primary btn-lg" %>
        </div>
      </div>

       <div class=" col-sm-offset-2 col-sm-10">
         [ <%= link_to "Back to Home", articles_path %> ]
      </div>

    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class='container'>
  <footer class = 'footer'>
    <small>
      Copyright &copy: <a href="//swiftads.com.au">SwiftAds</a>
      by <a href="//swiftads.com.au">David Mesaros </a>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class ='row'>
  <div class = "col-xs-8 col-xs-offset-2">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/_navs.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <div class="navbar-brand"  id = "logo">-->
        <%= link_to "Alpha Blog", root_path, :class => "navbar-brand" , :id => 'logo' %>
      <!--</div> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %>
        <li><%= link_to "Users List", users_path %></li>
            <% if logged_in? %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "All Categories", categories_path %></li>
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
                <% if logged_in? and current_user.admin? %>
                    <li role="separator" class="divider"></li>
                  <li><%= link_to "Create New Category", new_category_path %></li>

                    <% end %>




                  <li><%= link_to "New Article", new_article_path %> </li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile  || <%= "Admin " if current_user.admin %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit your Profile", edit_user_path(current_user) %></li>
                <li><%= link_to "View your profile", user_path(current_user) %></li>
              </ul>
              <% else %>
              <li><%= link_to "Log In", login_path %></li>
              <li><%= link_to "Sign Up", signup_path %></li>
              <% end %>

        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navs' %>
  <%= render 'layouts/messages' %>
  <div class ='container'>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
   <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages_flash.html.erb
<% if obj.errors.any? %>
   <div class ='row'>
    <div class= "col-xs-8 col-xs-offset-2">
      <div class = "panel panel-danger">
        <div class = "panel-heading">
          <h2 class = "panel-title">
            
            The following <%= pluralize(obj.errors.count, "error") %> 
          </h2>
          <div class= "panel-body">

            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                <% end %>
            </ul>
           </div>
         </div>
       </div>
     </div>
   </div>
 <% end %>

app/views/users/_form.html.erb
<div class='row'>
  <div class="col-xs-10">
    <%= form_for(@user, :html => {:class => "form-horizontal", role: "form" }) do |f| %>
      <div class='form-group'>
        <div class="control-label col-sm-2">
            <%= f.label :username%>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :username, :class=> "form-control", :placeholder => "Username" , :autofocus => true%>
        </div>
      </div>
      <div class='form-group'>
        <div class="control-label col-sm-2">
            <%= f.label :email %>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :email, :class=> "form-control", :placeholder => "Email" , :autofocus => true %>
        </div>
      </div>
      <div class='form-group'>
        <div class="control-label col-sm-2">
            <%= f.label :password_digest %>
         </div>
        <div class="col-sm-10">
            <%= f.password_field :password_digest, :class=> "form-control", :placeholder => "Enter Password" , :autofocus => true %>
        </div>
      </div>
      <div class='form-group'>
        <div class=" col-sm-offset-2 col-sm-10">
            <%= f.submit(@user.new_record? ? "Sign Up" : "Update your Account Buddy", :class => "btn btn-primary btn-lg") %>
        </div>
      </div>

       <div class=" col-sm-offset-2 col-sm-10">
         [ <%= link_to "Back to Home", articles_path %> ]
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align='center' > Edit Sign Up form </h1>
<% @user = @edit  || @user = @update %>
<%= render 'shared/error_messages_flash' , obj: @user %>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align= 'center'> All my List if Users </h1>

 <div align = 'center'>
    <%= will_paginate @All_users,  :renderer => BootstrapPagination::Rails%>
     <% @All_users.each do |userList| %>
      <ul class= 'listing'>
        <div class= "row" >
          <div class= "well col-md-4 col-md-offset-4">
            <li><%= link_to gravator_for(userList, :size => 100), user_path(userList) %></li>
            <li class= 'article-title'><%= link_to userList.username, user_path(userList) %> </li>
            <li><small><%= pluralize(userList.articles.count, 'article') if userList.articles %> </small></li>
            <% if logged_in? && current_user.admin? %>
                <li><%= link_to "Delete this User", user_path(userList), method: :delete, data: {confirm: 'Are you sure buddy delete the User and all its articles'} %></li>
            <% end %>
          </div>
        </div>
      </ul>
      <% end %>
    </div>

app/views/users/new.html.erb
<h1 align='center' > Sign Up form </h1>
<% @user = @new_user || @user = @create_user %>
<%= render 'shared/error_messages_flash' , obj: @user %>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align='center'> Welcome to <%= @show.username %> 's page => going to user_article</h1>
<div class = 'row' >
  <div class= 'col-md-4 col-md-offset-4 center'>
    <%= gravator_for @show , size: 150  %>
  </div>
</div>

<h4 align='center'><%= @show.username %> articles</h4>

 
<%= render "articles/user_articles" , obj: @show_articles %>
<%= will_paginate @show_articles,  :renderer => BootstrapPagination::Rails%>

app/views/welcome/index.html.erb
<div class=" center jumbotron">
    <h1>Alpha Blog</h1>
    <br>
    <canvas align="center"id="myChart" width="200" height="200"></canvas>
    <% if !logged_in? %>
    <%= link_to "Sign Up Now", signup_path, :class => "btn btn-warning btn-lg btn-xlarge" %>
    <% end %>
</div>